import turtle

myturtle= turtle.Turtle()
myturtle.penup()
myturtle.goto(50,75)
myturtle.pendown()
myturtle.forward(69)
myturtle.left(90)
myturtle.forward(69)
myturtle.left(90)
myturtle.forward(69)
myturtle.left(90)
myturtle.forward(69)
myturtle.left(90)
turtle.done()